#!/usr/bin/env python3
"""Generate the OpenRadioss implicit linear-static (MUMPS) cantilever test decks.

Writes cantilever_0000.rad (Starter) and cantilever_0001.rad (Engine) next to
this script and prints the closed-form expected displacements.

Model: flat cantilever plate strip in the XY plane, clamped at x=0, out-of-plane
tip load (+Z) at x=L.  Poisson's ratio is 0, so the plate solution is exactly
the Euler-Bernoulli beam solution (no anticlastic coupling).

Units: Mg, mm, s  ->  force N, stress MPa.
Card layouts follow /BEGIN version 2019 (same as qa-tests SMOKE_TEST/TWISBEAM).
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = "cantilever"

# ---------------------------------------------------------------- parameters
L, B, T = 100.0, 10.0, 1.0      # length (x), width (y), thickness [mm]
NX, NY = 40, 4                  # elements along x and across y (2.5 mm squares)
E, NU, RHO = 200000.0, 0.0, 7.85e-9   # MPa, -, Mg/mm^3
P = 1.0                         # total tip force [N], +Z
TSTOP = 1.0                     # implicit linear = one increment 0 -> TSTOP
ISHELL = 24                     # 24 = QEPH (CZKE3); 12 = QBAT (CBAKE3)
NIP = 5                         # integration points through thickness

LINE = "#---1----|----2----|----3----|----4----|----5----|----6----|----7----|----8----|----9----|---10----|"


# ---------------------------------------------------------------- formatting
def i10(v):
    s = f"{int(v):10d}"
    assert len(s) == 10, s
    return s


def f20(v):
    s = f"{v:.12g}".replace("e", "E")
    if not any(c in s for c in ".EN"):   # always write a decimal point: "1" -> "1.0"
        s += ".0"
    s = f"{s:>20}"
    assert len(s) == 20, s
    return s


def a10(s):
    s = f"{s:>10}"
    assert len(s) == 10, s
    return s


def node_id(i, j):
    return i * (NY + 1) + j + 1


def elem_id(i, j):
    return i * NY + j + 1


def id_lines(ids, per_line=10):
    out = []
    for k in range(0, len(ids), per_line):
        out.append("".join(i10(n) for n in ids[k:k + per_line]))
    return out


# ---------------------------------------------------------------- analytics
EI = E * B * T ** 3 / 12.0
G = E / (2.0 * (1.0 + NU))
KAPPA = 5.0 / 6.0


def w_bernoulli(x):
    return P * x * x * (3.0 * L - x) / (6.0 * EI)


def w_timoshenko(x):
    return w_bernoulli(x) + P * x / (KAPPA * G * B * T)


# ---------------------------------------------------------------- node sets
clamp = [node_id(0, j) for j in range(NY + 1)]
tip = [node_id(NX, j) for j in range(NY + 1)]
tip_corner = [tip[0], tip[-1]]
tip_inner = tip[1:-1]
jc = NY // 2
centre = [node_id(i, jc) for i in (NX // 4, NX // 2, 3 * NX // 4)]


def starter():
    s = []
    a = s.append
    a("#RADIOSS STARTER")
    a(LINE)
    a("# Cantilever plate strip - implicit LINEAR STATIC check of the MUMPS direct solver")
    a(f"# Units Mg-mm-s (N, MPa).  L={L:g}  b={B:g}  t={T:g}  E={E:g}  nu={NU:g}  P={P:g} N (+Z)")
    a(f"# Expected tip deflection  P*L^3/(3*E*I) = {w_bernoulli(L):.6f} mm   (I = b*t^3/12)")
    a("# Generated by make_cantilever.py - edit the script, not this file.")
    a(LINE)
    a("/BEGIN")
    a(ROOT)
    a("      2019         0")
    a("                  Mg                  mm                   s")
    a("                  Mg                  mm                   s")
    a(LINE)
    a("/TITLE")
    a("Cantilever plate strip - linear static implicit (MUMPS) verification")
    a(LINE)
    a("#  Implicit flag for the Starter (header-only card, hm_cfg_files/.../radioss110/CARDS/implicit.cfg)")
    a("/IMPLICIT")
    a(LINE)
    a("/MAT/ELAST/1")
    a("steel_nu0")
    a("#        Init. dens.          Ref. dens.")
    a(f20(RHO) + f20(0.0))
    a("#                  E                  nu")
    a(f20(E) + f20(NU))
    a(LINE)
    a("/PROP/SHELL/1")
    a(f"shell_t{T:g}")
    a("#   Ishell    Ismstr     Ish3n    Idrill                            P_thick_fail")
    a(i10(ISHELL) + i10(0) + i10(0) + i10(0) + " " * 20 + f20(0.0))
    a("#                 hm                  hf                  hr                  dm                  dn")
    a(f20(0.0) * 5)
    a("#        N   Istrain               Thick              Ashear              Ithick     Iplas")
    a(i10(NIP) + i10(1) + f20(T) + f20(0.0) + " " * 10 + i10(0) + i10(0))
    a(LINE)
    a("/PART/1")
    a("plate")
    a("#  prop_ID    mat_ID subset_ID")
    a(i10(1) + i10(1) + i10(0))
    a(LINE)
    a("/NODE")
    a("#  node_ID                  Xc                  Yc                  Zc")
    dx, dy = L / NX, B / NY
    for i in range(NX + 1):
        for j in range(NY + 1):
            a(i10(node_id(i, j)) + f20(i * dx) + f20(j * dy) + f20(0.0))
    a(LINE)
    a("/SHELL/1")
    a("# shell_ID  node_ID1  node_ID2  node_ID3  node_ID4")
    for i in range(NX):
        for j in range(NY):
            a(i10(elem_id(i, j)) + i10(node_id(i, j)) + i10(node_id(i + 1, j))
              + i10(node_id(i + 1, j + 1)) + i10(node_id(i, j + 1)))
    a(LINE)
    a("#  Clamp: all 6 DOF fixed at x = 0")
    a("/BCS/1")
    a("clamp_x0")
    a("#  Tra rot   skew_ID  grnod_ID")
    a("   111 111" + i10(0) + i10(1))
    a("/GRNOD/NODE/1")
    a("clamp_nodes_x0")
    s.extend(id_lines(clamp))
    a(LINE)
    a("#  Constant load function (value 1 for all t, so the load is P at t = TSTOP)")
    a("/FUNCT/1")
    a("constant_one")
    a("#                  X                   Y")
    a(f20(0.0) + f20(1.0))
    a(f20(100.0 * TSTOP) + f20(1.0))
    a(LINE)
    a(f"#  Tip load P = {P:g} N in +Z, consistent edge distribution: P/{2 * NY} at corners, P/{NY} inside")
    a("/CLOAD/1")
    a("tip_corner_nodes")
    a("#funct_IDT       Dir   skew_ID sensor_ID  grnod_ID                       Ascalex             Fscaley")
    a(i10(1) + a10("Z") + i10(0) + i10(0) + i10(2) + " " * 10 + f20(1.0) + f20(P / (2 * NY)))
    a("/GRNOD/NODE/2")
    a("tip_corner_nodes")
    s.extend(id_lines(tip_corner))
    a("/CLOAD/2")
    a("tip_inner_nodes")
    a("#funct_IDT       Dir   skew_ID sensor_ID  grnod_ID                       Ascalex             Fscaley")
    a(i10(1) + a10("Z") + i10(0) + i10(0) + i10(3) + " " * 10 + f20(1.0) + f20(P / NY))
    a("/GRNOD/NODE/3")
    a("tip_inner_nodes")
    s.extend(id_lines(tip_inner))
    a(LINE)
    a("/TH/NODE/1")
    a("centreline_and_tip_displacement")
    a("#      var       var       var")
    a(f"{'DX':<10}{'DY':<10}{'DZ':<10}")
    a("#  node_ID   skew_ID node_name")
    for n, i in zip(centre, (NX // 4, NX // 2, 3 * NX // 4)):
        a(i10(n) + i10(0) + f"x{i * dx:g}_centre")
    for j, n in enumerate(tip):
        a(i10(n) + i10(0) + f"tip_y{j * dy:g}")
    a("/TH/NODE/2")
    a("clamp_reactions")
    a("#      var       var       var")
    a(f"{'REACX':<10}{'REACY':<10}{'REACZ':<10}")
    a("#  node_ID   skew_ID node_name")
    for j, n in enumerate(clamp):
        a(i10(n) + i10(0) + f"clamp_y{j * dy:g}")
    a(LINE)
    a("/END")
    return s


def engine():
    s = []
    a = s.append
    a("#RADIOSS ENGINE")
    a(LINE)
    a("# Implicit linear static, MUMPS direct solver.  One increment from t=0 to TSTOP.")
    a(LINE)
    a(f"/RUN/{ROOT}/1")
    a(f20(TSTOP))
    a(LINE)
    a("#  Linear static (no /IMPL/DYNA -> static; /IMPL/LINEAR -> ILINE=1, one step DT=TSTOP)")
    a("/IMPL/LINEAR")
    a("#  Linear solver 2 = direct MUMPS (internally ISOLV=3 with IMUMPSV=1)")
    a("/IMPL/SOLVER/2")
    a("#    IPREC     L_LIM      ITOL               L_TOL")
    a(i10(0) + i10(0) + i10(0) + f20(0.0))
    a("#  Print the direct-solver relative residual ||K.u-F||/||F|| to listing and stdout")
    a("/IMPL/PRINT/LINEAR/-1")
    a("#  MUMPS ICNTL(3)=listing unit, ICNTL(4)=2 (errors, warnings, main statistics)")
    a("/IMPL/MUMPS/MSGLV/2")
    a(LINE)
    a("/PRINT/-1")
    a("/TFILE/4")
    a("#             dT_HIS")
    a(f20(TSTOP / 2))
    a("/ANIM/DT")
    a("#             Tstart               Tfreq")
    a(f20(0.0) + f20(TSTOP / 2))
    a("/ANIM/VECT/DISP")
    a("#  ASCII nodal displacement dump (cantilever_000n.sty), first one at t >= Tstart")
    a("/OUTP/DT")
    a("#             Tstart               Tfreq")
    a(f20(TSTOP / 2) + f20(TSTOP / 2))
    a("/OUTP/VECT/DISP")
    return s


def write(name, lines):
    for ln in lines:
        assert len(ln) <= 100, f"{name}: line longer than 100 chars: {ln!r}"
    (HERE / name).write_text("\n".join(lines) + "\n", encoding="ascii", newline="\n")


if __name__ == "__main__":
    write(f"{ROOT}_0000.rad", starter())
    write(f"{ROOT}_0001.rad", engine())
    nn, ne = (NX + 1) * (NY + 1), NX * NY
    print(f"wrote {ROOT}_0000.rad ({nn} nodes, {ne} shells) and {ROOT}_0001.rad")
    print(f"EI = {EI:.6g} N.mm2, free DOF = {6 * (nn - len(clamp))}")
    print("expected DZ (Euler-Bernoulli / Timoshenko):")
    for x in (L / 4, L / 2, 3 * L / 4, L):
        print(f"  x = {x:6.1f} mm : {w_bernoulli(x):.6f} / {w_timoshenko(x):.6f} mm")
